/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        overpass: ["Overpass", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
      },
      // colors: {
      //   black: "var(--color-black)",
      //   white: "var(--color-white)",
      //   red: "var(--color-red)",
      //   peach: "var(--color-peach)",
      //   orange: "var(--color-orange)",
      //   yellow: "var(--color-yellow)",
      //   green: "var(--color-green)",
      //   overlay: "var(--color-overlay)",
      //   shadow: {
      //     DEFAULT: "var(--color-shadow)",
      //     dark: "var(--color-shadow-dark)",
      //     blue: "var(--color-shadow-blue)",
      //   },
      //   text: {
      //     DEFAULT: "var(--color-text)",
      //     light: "var(--color-text-light)",
      //     lighter: "var(--color-text-lighter)",
      //     bright: "var(--color-text-bright)",
      //   },
      //   foreground: {
      //     DEFAULT: "var(--color-foreground)",
      //     grey: "var(--color-foreground-grey)",
      //     blue: "var(--color-foreground-blue)",
      //     "grey-dark": "var(--color-foreground-grey-dark)",
      //     "blue-dark": "var(--color-foreground-blue-dark)",
      //   },
      //   background: {
      //     DEFAULT: "var(--color-background)",
      //     "blue-dark": "var(--color-background-blue-dark)",
      //     100: "var(--color-background-100)",
      //     200: "var(--color-background-200)",
      //     300: "var(--color-background-300)",
      //     400: "var(--color-background-400)",
      //     500: "var(--color-background-500)",
      //     600: "var(--color-background-600)",
      //     700: "var(--color-background-700)",
      //     800: "var(--color-background-800)",
      //     900: "var(--color-background-900)",
      //     1000: "var(--color-background-1000)",
      //     1100: "var(--color-background-1100)",
      //     1200: "var(--color-background-1200)",
      //   },
      //   gray: {
      //     100: "var(--color-gray-100)",
      //     200: "var(--color-gray-200)",
      //     300: "var(--color-gray-300)",
      //     400: "var(--color-gray-400)",
      //     500: "var(--color-gray-500)",
      //     600: "var(--color-gray-600)",
      //     700: "var(--color-gray-700)",
      //     800: "var(--color-gray-800)",
      //     900: "var(--color-gray-900)",
      //     1000: "var(--color-gray-1000)",
      //     1100: "var(--color-gray-1100)",
      //     1200: "var(--color-gray-1200)",
      //   },
      //   blue: {
      //     DEFAULT: "var(--color-blue)",
      //     dim: "var(--color-blue-dim)",
      //     100: "var(--color-blue-100)",
      //     200: "var(--color-blue-200)",
      //     300: "var(--color-blue-300)",
      //     400: "var(--color-blue-400)",
      //     500: "var(--color-blue-500)",
      //     600: "var(--color-blue-600)",
      //     700: "var(--color-blue-700)",
      //     800: "var(--color-blue-800)",
      //     900: "var(--color-blue-900)",
      //     1000: "var(--color-blue-1000)",
      //   },
      //   green: {
      //     100: "var(--color-green-100)",
      //     200: "var(--color-green-200)",
      //     300: "var(--color-green-300)",
      //     400: "var(--color-green-400)",
      //     500: "var(--color-green-500)",
      //     600: "var(--color-green-600)",
      //     700: "var(--color-green-700)",
      //     800: "var(--color-green-800)",
      //   },
      //   red: {
      //     100: "var(--color-red-100)",
      //     200: "var(--color-red-200)",
      //     300: "var(--color-red-300)",
      //     400: "var(--color-red-400)",
      //     500: "var(--color-red-500)",
      //     600: "var(--color-red-600)",
      //     700: "var(--color-red-700)",
      //   },
      // },
    },
  },
  plugins: [],
};
